### PR TITLE
revert: remove @typescript-eslint/strict-boolean-expressions

### PR DESCRIPTION
**Pull request by lukashass**
introducing this was a breaking change
to properly introduce this it needs to be configured less strict
reverts #5

### CODE REVIEW

**Comment by mariusheine** [comment]
@lukashass Why do want to revert that?

**Comment by lukashass** [comment]
@mariusheine We do not use it anywhere, yet. I want to update a project to the newest version of this config.
This rule is configured way too strict. #5 was sort of merged by accident as I forgot to mark this strict config as draft.

**Comment by mariusheine** [comment]
@lukashass I actually liked it. I had such a situation from time to time and it somehow helps to avoid weird situations when e.g. in the following situation

```
const a: boolean | undefined = undefined;
if (!a) {
  console.warn('No value provided for a');
}
```

The console warn is somehow wrong if we would have `a = false;`. This would never happen if we keep strict boolean expressions active

**Review by mariusheine — APPROVED** [review]

**Comment by lukashass** [comment]
We will track reintroduction in #38

**Pull request merged**
