### PR TITLE
feat: remove eslint-plugin-prettier

### PR DESCRIPTION
**Pull request by lukashass**
In preparation to using format on save instead of showing prettier errors.

### CODE REVIEW

**Comment by anbraten** [comment]
What is the change doing?

**Comment by lukashass** [comment]
@anbraten eslint will no longer show prettier errors. I hope this combined with automatically formatting a file with prettier on save will reduce mental load of developers.

**Comment by anbraten** [comment]
@lukashass Ahh okay, I thought that was needed so eslint knows the prettier format.

**Comment by lukashass** [comment]
@anbraten Thats what eslint-__config__-prettier is for. It ensures compatibility.

**Review by anbraten — APPROVED** [review]

**Pull request merged**
